const bookList = [
    { id: 1, type: "book", name: "Genesis" },
    { id: 2, type: "book", name: "Exodus" },
    { id: 3, type: "book", name: "Leviticus" },
    { id: 4, type: "book", name: "Numbers" },
    { id: 5, type: "book", name: "Deuteronomy" },
    { id: 6, type: "book", name: "Joshua" },
    { id: 7, type: "book", name: "Judges" },
    { id: 8, type: "book", name: "Ruth" },
    { id: 9, type: "book", name: "1 Samuel" },
    { id: 10, type: "book", name: "2 Samuel" },
    { id: 11, type: "book", name: "1 Kings" },
    { id: 12, type: "book", name: "2 Kings" },
    { id: 13, type: "book", name: "1 Chronicles" },
    { id: 14, type: "book", name: "2 Chronicles" },
    { id: 15, type: "book", name: "Ezra" },
    { id: 16, type: "book", name: "Nehemiah" },
    { id: 17, type: "book", name: "Esther" },
    { id: 18, type: "book", name: "Job" },
    { id: 19, type: "book", name: "Psalms" },
    { id: 20, type: "book", name: "Proverbs" },
    { id: 21, type: "book", name: "Ecclesiastes" },
    { id: 22, type: "book", name: "Song of Solomon" },
    { id: 23, type: "book", name: "Isaiah" },
    { id: 24, type: "book", name: "Jeremiah" },
    { id: 25, type: "book", name: "Lamentations" },
    { id: 26, type: "book", name: "Ezekiel" },
    { id: 27, type: "book", name: "Daniel" },
    { id: 28, type: "book", name: "Hosea" },
    { id: 29, type: "book", name: "Joel" },
    { id: 30, type: "book", name: "Amos" },
    { id: 31, type: "book", name: "Obadiah" },
    { id: 32, type: "book", name: "Jonah" },
    { id: 33, type: "book", name: "Micah" },
    { id: 34, type: "book", name: "Nahum" },
    { id: 35, type: "book", name: "Habakkuk" },
    { id: 36, type: "book", name: "Zephaniah" },
    { id: 37, type: "book", name: "Haggai" },
    { id: 38, type: "book", name: "Zechariah" },
    { id: 39, type: "book", name: "Malachi" },
    { id: 40, type: "book", name: "Matthew" },
    { id: 41, type: "book", name: "Mark" },
    { id: 42, type: "book", name: "Luke" },
    { id: 43, type: "book", name: "John" },
    { id: 44, type: "book", name: "Acts" },
    { id: 45, type: "book", name: "Romans" },
    { id: 46, type: "book", name: "1 Corinthians" },
    { id: 47, type: "book", name: "2 Corinthians" },
    { id: 48, type: "book", name: "Galatians" },
    { id: 49, type: "book", name: "Ephesians" },
    { id: 50, type: "book", name: "Philippians" },
    { id: 51, type: "book", name: "Colossians" },
    { id: 52, type: "book", name: "1 Thessalonians" },
    { id: 53, type: "book", name: "2 Thessalonians" },
    { id: 54, type: "book", name: "1 Timothy" },
    { id: 55, type: "book", name: "2 Timothy" },
    { id: 56, type: "book", name: "Titus" },
    { id: 57, type: "book", name: "Philemon" },
    { id: 58, type: "book", name: "Hebrews" },
    { id: 59, type: "book", name: "James" },
    { id: 60, type: "book", name: "1 Peter" },
    { id: 61, type: "book", name: "2 Peter" },
    { id: 62, type: "book", name: "1 John" },
    { id: 63, type: "book", name: "2 John" },
    { id: 64, type: "book", name: "3 John" },
    { id: 65, type: "book", name: "Jude" },
    { id: 66, type: "book", name: "Revelation" },
  ];

  export default bookList;